[build]
  command = """
    set -e
    echo "=== Starting Blog build process ==="
    echo "Node version: $(node --version)"
    echo "npm version: $(npm --version)"
    echo "Hugo version: $(hugo version)"
    echo "Go version: $(go version || echo 'Go not available')"
    
    echo "=== Installing dependencies ==="
    npm cache clean --force
    npm install --omit=dev --legacy-peer-deps --verbose
    
    echo "=== Running Hugo build ==="
    hugo --gc --minify -b $URL --logLevel debug --printI18nWarnings --printPathWarnings
    
    echo "=== Running Pagefind indexing ==="
    npx --yes pagefind@1.1.0 --source 'public' --verbose
    
    echo "=== Build completed successfully ==="
  """
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.150.1"
  GO_VERSION = "1.21.5"
  NODE_VERSION = "20"
  HUGO_ENABLEGITINFO = "true"
  HUGO_LOG_I18N_WARNINGS = "true"
  HUGO_LOG_WARNINGS = "true"
  FORCE_COLOR = "1"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = """
    set -e
    echo "=== Deploy Preview Build ==="
    echo "Deploy URL: $DEPLOY_PRIME_URL"
    npm cache clean --force
    npm install --omit=dev --legacy-peer-deps --verbose
    hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL --logLevel debug --printI18nWarnings --printPathWarnings
    npx --yes pagefind@1.1.0 --source 'public' --verbose
  """

[context.branch-deploy]
  command = """
    set -e
    echo "=== Branch Deploy Build ==="
    echo "Deploy URL: $DEPLOY_PRIME_URL"
    npm cache clean --force
    npm install --omit=dev --legacy-peer-deps --verbose
    hugo --gc --minify -b $DEPLOY_PRIME_URL --logLevel debug --printI18nWarnings --printPathWarnings
    npx --yes pagefind@1.1.0 --source 'public' --verbose
  """

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true
